#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.24.3'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.empty(10)

array([            nan,             nan, 5.98117618e-114, 1.96565562e-062,
       6.01334504e-154, 1.35717430e+131, 8.95393586e-096, 5.98149210e-154,
       6.01347002e-154, 6.35226583e-067])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
print(np.empty(10).size * np.empty(10).itemsize)
print(np.empty(10).nbytes)

80
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
empty_a=np.zeros(10).reshape(10,1)
empty_a[5]=1
print(empty_a)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
ranging=np.arange(10,49)
print(ranging)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
vec=np.array([1,2,3,4])
print(vec)
reverse_vec=vec[::-1]
print(reverse_vec)

[1 2 3 4]
[4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
matrix1=np.arange(0,9).reshape(3,3)
print(matrix1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [9]:
np.nonzero(np.array([1,2,0,0,4,0]))

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [11]:
matrix2=np.random.randint(1,20,27).reshape(3,3,3)
print(matrix2)

[[[10  7 18]
  [ 3 17  3]
  [15  9 18]]

 [[18  7  3]
  [ 3 11  9]
  [ 8  7  1]]

 [[15 12  8]
  [17  5 16]
  [17  2 12]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [12]:
matrix3=np.random.rand(10,10)
print(matrix3)
print("the minimum number in this array : " , np.min(matrix3))
print("the maximum number in this array : " , np.max(matrix3))

[[0.07316157 0.2328658  0.68398965 0.49263794 0.10684324 0.66609895
  0.05978883 0.77248952 0.0565577  0.6334625 ]
 [0.89079532 0.53892501 0.96128114 0.65435031 0.72213796 0.82846086
  0.98085838 0.57982758 0.31118742 0.67091615]
 [0.22017143 0.9018985  0.95949051 0.79325479 0.22418047 0.93099471
  0.45723509 0.52086335 0.09610686 0.83356654]
 [0.79451044 0.90359891 0.35504355 0.87207369 0.78756959 0.7774847
  0.68437902 0.40929747 0.86239564 0.34111072]
 [0.77086321 0.22467848 0.83342154 0.45514576 0.26093021 0.83303685
  0.13046173 0.43919938 0.87952913 0.97549601]
 [0.25874123 0.72994581 0.13046536 0.00751819 0.74447038 0.04878113
  0.04948215 0.38437097 0.45674333 0.09121277]
 [0.36905676 0.80515659 0.63109774 0.05831013 0.19593933 0.54362888
  0.39803105 0.37285442 0.31761696 0.89033699]
 [0.89127797 0.83201848 0.66744641 0.38171534 0.84097349 0.98957157
  0.47604038 0.27104988 0.40167385 0.36557286]
 [0.78259984 0.88857888 0.23963095 0.26667355 0.48325692 0.71658904
  0.59564473 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [13]:
vec1=np.random.randint(0,20,30)
print(vec1)
print("the mean value of this vector : " , np.mean(vec1))

[ 0  5  2  1 14 18 18  0 10  3 19  3  4 19 14  7  5  0 19 17  3 18 19 17
  0 12  1  6  3  0]
the mean value of this vector :  8.566666666666666


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
a = np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [15]:
a = np.ones((5,5))
a = np.pad(a,1)
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [16]:
#0 * np.nan -> np.nan (because anything by np.nan = np.nan)
#np.nan==np.nan -> False (because in numpy np.nan not equal itself )
#np.inf>np.nan ->False
#np.nan-np.nan -> np.nan (because anything subtract np.nan gives np.nan)
#np.nan in set([np.nan]) ->True
#0.3 == 3*0.1 -> False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [17]:
matrix4=np.zeros((5,5))
print(matrix4)
print()
nums=[1,2,3,4]
np.fill_diagonal(matrix4[1:],nums)
print(matrix4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [18]:
matrix5=np.zeros((8,8))
matrix5[::2,::2]=1
matrix5[1::2,1::2]=1
print(matrix5)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [19]:
inDex=np.unravel_index(100,(6,7,8))
print(inDex)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [20]:
matrix6=np.array([[0,1],[1,0]])
matrix7=np.tile(matrix6,(4,4))
print(matrix7)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [21]:
matrix7=np.random.randint(1,20,25).reshape(5,5)
print(matrix7)
print()
maximum=np.max(matrix7)
minimum=np.min(matrix7)
normalization=(matrix7-minimum)/(maximum-minimum)
print("The normalized matrix : \n " ,normalization )

[[ 5  7 18 14  5]
 [ 7  9 14  3  7]
 [ 9 11  4 11 11]
 [17 14 11 14 17]
 [ 2  8 10  6  1]]

The normalized matrix : 
  [[0.23529412 0.35294118 1.         0.76470588 0.23529412]
 [0.35294118 0.47058824 0.76470588 0.11764706 0.35294118]
 [0.47058824 0.58823529 0.17647059 0.58823529 0.58823529]
 [0.94117647 0.76470588 0.58823529 0.76470588 0.94117647]
 [0.05882353 0.41176471 0.52941176 0.29411765 0.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [22]:
custom_dtype=np.dtype([('red' ,np.uint8 ),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
colors=np.array((255,0,0,128),dtype=custom_dtype)
print(colors)
red_color=colors['red']
green_color=colors['green']
blue_color=colors['blue']
alpha_color=colors['alpha']
print(f"red {red_color} \n green {green_color} \n blue {blue_color} \n alpha {alpha_color}")

(255, 0, 0, 128)
red 255 
 green 0 
 blue 0 
 alpha 128


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [23]:
matrix8=np.random.randint(0,10,15).reshape(5,3)
matrix9=np.random.randint(0,10,6).reshape(3,2)
matrix10=np.dot(matrix8,matrix9)
print(matrix10)

[[ 61  65]
 [ 77  43]
 [ 21  23]
 [111 112]
 [ 44  51]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [24]:
matrix11=np.random.randint(0,10,10)
num=(matrix11>=3) & (matrix11<=8)
matrix11[num] *= -1
print(matrix11)

[ 9  1 -7  0 -3 -3 -5 -4 -5  1]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [25]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [26]:
#z**z , 2<<z>>2 , z <- z , 1j*z  and z/1/1 (legal)
#z<z>z (illegal)

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [27]:
#np.array(0) / np.array(0) will give me a nan
#np.array(0) // np.array(0) will give me an error because it divided by zero which is illegal (undefined)
#np.array([np.nan]).astype(int).astype(float)  will give me array with one element contains 0.0 (as a float number)

#### 29. How to round away from zero a float array ? (★☆☆)

In [28]:
arrayy=np.array([3.4,2.3,5.7,3.6,23.1])
float_up=np.ceil(arrayy)
float_down=np.floor(arrayy)
print(arrayy)
print(float_up)
print(float_down)

[ 3.4  2.3  5.7  3.6 23.1]
[ 4.  3.  6.  4. 24.]
[ 3.  2.  5.  3. 23.]


#### 30. How to find common values between two arrays? (★☆☆)

In [29]:
array1=np.array([1,7,2,5,24])
array2=np.array([1,87,5,65,2])
array_intersect=np.intersect1d(array1,array2)
print(array_intersect)

[1 2 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [30]:
#np.warning.filterwarnings('ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [31]:
#no ,first expression will result a complex number which is ij
#    second expression will result a nan

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [32]:
from datetime import datetime , timedelta
today =datetime.now().date()
yesterday = today -timedelta(days=1)
tomorrow=today +timedelta(days=1)
print("yesterday : ",yesterday )
print("today : ",today)
print("tomorrow : ",tomorrow)

yesterday :  2024-01-12
today :  2024-01-13
tomorrow :  2024-01-14


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [33]:
import numpy as np
import datetime
start_date = datetime.date(2016, 7, 1)
end_date = datetime.date(2016, 7, 31)
dates = np.arange(start_date, end_date + datetime.timedelta(days=1), datetime.timedelta(days=1))
for date in dates :
  print(date)

2016-07-01T00:00:00.000000
2016-07-02T00:00:00.000000
2016-07-03T00:00:00.000000
2016-07-04T00:00:00.000000
2016-07-05T00:00:00.000000
2016-07-06T00:00:00.000000
2016-07-07T00:00:00.000000
2016-07-08T00:00:00.000000
2016-07-09T00:00:00.000000
2016-07-10T00:00:00.000000
2016-07-11T00:00:00.000000
2016-07-12T00:00:00.000000
2016-07-13T00:00:00.000000
2016-07-14T00:00:00.000000
2016-07-15T00:00:00.000000
2016-07-16T00:00:00.000000
2016-07-17T00:00:00.000000
2016-07-18T00:00:00.000000
2016-07-19T00:00:00.000000
2016-07-20T00:00:00.000000
2016-07-21T00:00:00.000000
2016-07-22T00:00:00.000000
2016-07-23T00:00:00.000000
2016-07-24T00:00:00.000000
2016-07-25T00:00:00.000000
2016-07-26T00:00:00.000000
2016-07-27T00:00:00.000000
2016-07-28T00:00:00.000000
2016-07-29T00:00:00.000000
2016-07-30T00:00:00.000000
2016-07-31T00:00:00.000000


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [34]:
A=np.array([1,2,3],dtype=np.float16)
B=np.array([5,6,7],dtype=np.float16)
A += B
A *= -0.5
print(A)

[-3. -4. -5.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [35]:
rand_array=np.random.rand(5) * 10
intrand=rand_array.astype(int)
print("method 1: " ,intrand)
intrand2=np.floor(rand_array)
print("method 2: ",intrand2)
intrand3=[int(x) for x in rand_array]
print("method 3: ",intrand3)
intrand4=np.trunc(rand_array)
print("method 4: ",intrand4)

method 1:  [4 9 3 1 7]
method 2:  [4. 9. 3. 1. 7.]
method 3:  [4, 9, 3, 1, 7]
method 4:  [4. 9. 3. 1. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [36]:
matrix13=np.tile(range(5),(5,1))
print(matrix13)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [37]:
def generator():
  for i in range(1,11):
    yield i
array22=np.array(list(generator()))
print(array22)

[ 1  2  3  4  5  6  7  8  9 10]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [38]:
vec22=np.linspace(0,1,12)
vec22=vec22[1:-1]
vec22

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [39]:
vec2=np.random.randint(0,10,10)
print(vec2)
vec3=sorted(vec2)
print(vec3)

[6 4 1 2 5 3 0 7 3 5]
[0, 1, 2, 3, 3, 4, 5, 5, 6, 7]


#### 41. Consider two random array A and B, check if they are equal (★★☆)

In [40]:
matrix20=np.array([1,2,3])
matrix21=np.array([1,2,3])
print(np.array_equal(matrix20,matrix21))

True


#### 42. Make an array immutable (read-only) (★★☆)

In [41]:
arr=np.array([1,2,3,4])
arr.flags.writeable=False
arr[0]=2
arr

ValueError: assignment destination is read-only

#### 43. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [42]:
cartesian=np.random.rand(10,2)
print("The cartesian coordinates :")
print(cartesian,"\n")
x = cartesian[:,0]
y = cartesian[:,1]

r = np.sqrt(x**2,y**2)
anglee=np.arctan2(y,x)
angle_deg=np.degrees(anglee)
polar=np.column_stack((r,angle_deg))
print("The polar coordinates :")
print(polar)

The cartesian coordinates :
[[0.38926857 0.56263596]
 [0.61893322 0.48390979]
 [0.36327221 0.64679368]
 [0.24645011 0.89506483]
 [0.60167765 0.63526957]
 [0.87124145 0.65770966]
 [0.28456551 0.89462092]
 [0.53987374 0.99661784]
 [0.75334112 0.53135181]
 [0.87506898 0.81407756]] 

The polar coordinates :
[[ 0.38926857 55.32196577]
 [ 0.61893322 38.01989337]
 [ 0.36327221 60.67921913]
 [ 0.24645011 74.60546314]
 [ 0.60167765 46.55560592]
 [ 0.87124145 37.04955266]
 [ 0.28456551 72.35491238]
 [ 0.53987374 61.55533432]
 [ 0.75334112 35.19634892]
 [ 0.87506898 42.93207196]]


#### 44. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [43]:
matr=np.random.randint(1,10,10)
print(matr)
maxi=np.argmax(matr)
matr[maxi]=0
print(matr)

[8 2 3 3 8 9 8 6 4 9]
[8 2 3 3 8 0 8 6 4 9]


#### 45. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [44]:
types=[('x',float),('y',float)]
coordinates=np.empty(10,dtype=types)
coordinates['x']=np.random.rand(10)
coordinates['y']=np.random.rand(10)
print(coordinates)

[(0.36318615, 0.53030491) (0.01118281, 0.61569622)
 (0.05827788, 0.83456187) (0.1758301 , 0.68062064)
 (0.1893212 , 0.87039342) (0.7071534 , 0.8787401 )
 (0.73185056, 0.42205009) (0.85221474, 0.34635915)
 (0.55958471, 0.97553532) (0.05028001, 0.39706241)]


#### 46. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [45]:
array1=np.array([7,8,9,10])
array2=np.array([1,2,3,4])
u=np.empty((len(array1),len(array2)))
for i in range(len(array1)):
  for j in range(len(array2)):
    if array1[i]-array2[j]!=0:
      u[i,j]=1/(array1[i]-array2[j])
    else:
      print("it will give an error because the dividing by zero ")
      break
print(u)

[[0.16666667 0.2        0.25       0.33333333]
 [0.14285714 0.16666667 0.2        0.25      ]
 [0.125      0.14285714 0.16666667 0.2       ]
 [0.11111111 0.125      0.14285714 0.16666667]]


#### 47. How to print all the values of an array? (★★☆)

In [49]:
array3=np.array([2,3,4,5])
for i in array3:
  print(i)

2
3
4
5


#### 48. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [50]:
scalar=8
matrix=np.array([23,-2,34,1])
value=matrix[np.argmin(abs(scalar-matrix))]
print(value)

1


#### 49. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [51]:
types=[('x',float),('y',float),('r',int),('g',int),('b',int)]
data = np.array([(1.0, 2.0, 255, 0, 0),(3.5, 4.5, 0, 255, 0),(0.0, 0.0, 0, 0, 255)],dtype=types)
print(f"Position 1: ({data['x'][0]}, {data['y'][0]})")
print(f"Color: (R={data['r'][0]}, G={data['g'][0]}, B={data['b'][0]})")
print(f"Position 2: ({data['x'][1]}, {data['y'][1]})")
print(f"Color: (R={data['r'][1]}, G={data['g'][1]}, B={data['b'][1]})")
print(f"Position 3: ({data['x'][2]}, {data['y'][2]})")
print(f"Color: (R={data['r'][2]}, G={data['g'][2]}, B={data['b'][2]})")

Position 1: (1.0, 2.0)
Color: (R=255, G=0, B=0)
Position 2: (3.5, 4.5)
Color: (R=0, G=255, B=0)
Position 3: (0.0, 0.0)
Color: (R=0, G=0, B=255)


#### 50. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [52]:
random_vector = np.random.rand(100, 2)
distances = np.zeros((100, 100))

for i in range(100):
    for j in range(100):
        distances[i, j] = np.sqrt((random_vector[i, 0] - random_vector[j, 0])**2 + (random_vector[i, 1] - random_vector[j, 1])**2)

print(distances)

[[0.         0.7475854  0.90738102 ... 0.35396768 0.31055708 0.42584625]
 [0.7475854  0.         0.19686975 ... 0.83469868 0.49185832 0.65528826]
 [0.90738102 0.19686975 0.         ... 1.02623254 0.6222253  0.73291164]
 ...
 [0.35396768 0.83469868 1.02623254 ... 0.         0.57136691 0.75707398]
 [0.31055708 0.49185832 0.6222253  ... 0.57136691 0.         0.24024914]
 [0.42584625 0.65528826 0.73291164 ... 0.75707398 0.24024914 0.        ]]


#### 51. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [53]:
float_array=np.array([1.99,23.4,98,4],dtype=np.float32)
intarray=float_array.astype(np.int32)
print(intarray)

[ 1 23 98  4]


#### 52. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [54]:
array4=np.array(([1,2,3],[24,5,6],[23,25,6]))
for index,value in np.ndenumerate(array4):
  print(f"index {index} , = value {value}")

index (0, 0) , = value 1
index (0, 1) , = value 2
index (0, 2) , = value 3
index (1, 0) , = value 24
index (1, 1) , = value 5
index (1, 2) , = value 6
index (2, 0) , = value 23
index (2, 1) , = value 25
index (2, 2) , = value 6


#### 53. Subtract the mean of each row of a matrix (★★☆)

In [55]:
matrix22=np.array(([1,2,3],[4,5,6],[7,8,9]))
matrix_mean=np.mean(matrix22,axis=1,keepdims=True)
matrix2=matrix-matrix_mean
print(matrix2)

[[ 21.  -4.  32.  -1.]
 [ 18.  -7.  29.  -4.]
 [ 15. -10.  26.  -7.]]


#### 54. How to sort an array by the nth column? (★★☆)

In [56]:
arr = [
 [1, 3, 2],
 [5, 1, 4],
 [3, 5, 1]
]

arr.sort(key=lambda x: x[1])

print(arr)

[[5, 1, 4], [1, 3, 2], [3, 5, 1]]


#### 55. How to tell if a given 2D array has null columns? (★★☆)

In [57]:
array=np.array(([1,0,1],[3,0,1],[23,0,3]))
null1=np.all(array==0,axis=0)
if np.any(null1):
  print("this array has null columns ")
else:
  print("this array does not have null columns")

this array has null columns 


#### 56. Find the nearest value from a given value in an array (★★☆)

In [58]:
matrix4=np.array([12,3,10,8])
value = 1
abss=np.abs(matrix4-value)
nearest_ind=np.argmin(abss)
nearest_value=matrix4[nearest_ind]
print(nearest_value)

3


#### 57. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [59]:
array2=np.array([[2,3,4]])
array5=np.array([[7],[8],[9]])
shape_arr2=array2.shape
shape_arr5=array5.shape
result=np.zeros((1,3))
if shape_arr2==(1,3) and shape_arr5==(3,1):
  for i in range(3):
    for j in range(3):
      result[0,i] +=array2[0,i]+array5[j,0]
print(array2)
print(array5)
print(result)

[[2 3 4]]
[[7]
 [8]
 [9]]
[[30. 33. 36.]]


#### 58. Create an array class that has a name attribute (★★☆)

In [60]:
class arrays:
  def __init__(self,name,data):
    self.name=name
    self.data=np.array(data)
name="Array"
num=[2,4,5]
array2=arrays(name,num)
print("The name if the array :",array2.name)
print("This array contains :",array2.data)

The name if the array : Array
This array contains : [2 4 5]


#### 59. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [61]:
vector1 = [2, 4, 1, 3, 6, 2]
index_vector = [1, 3, 4, 4]
index_count = {}
for index in index_vector:
    if index in index_count:
        index_count[index] += 1
    else:
        index_count[index] = 1
for index, count in index_count.items():
    vector1[index] += count
print(vector1)

[2, 5, 1, 4, 8, 2]


#### 60. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [62]:
X = np.array([1, 2, 3, 4, 5])
I = [2, 0, 1, 3, 2]
n = len(I)
F = np.zeros(n)
for i in range(n):
    F[i] += X[I[i]]
print(F)

[3. 1. 2. 4. 3.]


#### 61. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [63]:
arr=np.random.rand(4,3,2,2)
print(arr.shape)
summing=np.sum(arr,axis=(2,3))
print(arr)
print()
print(summing)

(4, 3, 2, 2)
[[[[0.62610914 0.67931015]
   [0.05091542 0.96521273]]

  [[0.00121942 0.36533196]
   [0.06836203 0.0148265 ]]

  [[0.36686111 0.36511006]
   [0.49634855 0.68163842]]]


 [[[0.34315805 0.07327088]
   [0.82150494 0.11668615]]

  [[0.27916266 0.61161209]
   [0.53493933 0.89890181]]

  [[0.60777257 0.91855243]
   [0.26846069 0.66027166]]]


 [[[0.025792   0.01186103]
   [0.28646814 0.64305881]]

  [[0.00905243 0.33432096]
   [0.49391976 0.06727385]]

  [[0.50973235 0.45715054]
   [0.14857606 0.18234034]]]


 [[[0.840465   0.24525299]
   [0.66653476 0.57255125]]

  [[0.76578642 0.68571927]
   [0.83181027 0.05704373]]

  [[0.34462276 0.62652883]
   [0.59294378 0.81253804]]]]

[[2.32154743 0.4497399  1.90995814]
 [1.35462001 2.32461588 2.45505736]
 [0.96717998 0.904567   1.29779929]
 [2.324804   2.34035969 2.3766334 ]]


#### 62. How to get the diagonal of a dot product? (★★★)

In [64]:
array6=np.array([[2,3],[8,4]])
array8=np.array([[7,10],[2,5]])
dot_product=np.dot(array6,array8)
diagonal=np.diag(dot_product)
print("array1 \n",array6)
print("array2 \n",array8)
print("the dot product : \n",dot_product)
print("the diagonal : \n",diagonal)

array1 
 [[2 3]
 [8 4]]
array2 
 [[ 7 10]
 [ 2  5]]
the dot product : 
 [[ 20  35]
 [ 64 100]]
the diagonal : 
 [ 20 100]


#### 63. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [65]:
arr1=np.array([2,3,4])
length=len(arr1)+(len(arr1)-1)*3
arr2=np.zeros(length)
arr2[::4]=arr1
print(arr2)

[2. 0. 0. 0. 3. 0. 0. 0. 4.]


#### 64. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [66]:
array1 = np.random.rand(5, 5, 3)
array2 = np.random.rand(5, 5)
result = array1 * array2[:, :, np.newaxis]
print(array1.shape)
print(array2.shape)
print(result.shape)

(5, 5, 3)
(5, 5)
(5, 5, 3)


#### 65. How to swap two rows of an array? (★★★)

In [68]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10,11,11]])
i = int(input("Enter the index of row you want to swap : "))
j = int(input("Enter the index of row you want to swap : "))

arr[i], arr[j] = arr[j].copy(), arr[i].copy()

print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [10 11 11]
 [ 7  8  9]]


#### 66. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [69]:
def generate_array_C(C):
    max_count = len(C) - 1
    A = []
    for count, freq in enumerate(C):
        A.extend([count] * freq)
    return np.array(A[:max_count])

C = np.array([0, 2, 1, 1, 0, 1])
A = generate_array_C(C)
print("C:", C)
print("A:", A)
print("Result of np.bincount(A):", np.bincount(A))

C: [0 2 1 1 0 1]
A: [1 1 2 3 5]
Result of np.bincount(A): [0 2 1 1 0 1]


#### 67. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [70]:
#boolean
boolean= True
boolean = not True
print(boolean)
#float
floatt=4.0
floatt=-floatt
print(floatt)

False
-4.0


#### 68. Compute a matrix rank (★★★)

In [71]:
matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
rank = np.linalg.matrix_rank(matrix)
print("Matrix A:")
print(matrix)
print(f"Rank of the matrix: {rank}")

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of the matrix: 2


#### 67. How to find the most frequent value in an array?

In [72]:
arr=np.array([1,2,4,2,4,1,4,4,6])
most_frequent=np.bincount(arr).argmax()
print(most_frequent)

4


#### 68. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [73]:
matrix = np.random.rand(10, 10) *10

blocks = []

for i in range(8):
    for j in range(8):
        block = matrix[i:i+3, j:j+3]
        blocks.append(block)
print("First 3x3 block:")
print(blocks[0])
print()
print("Second 3x3 block:")
print(blocks[1])

First 3x3 block:
[[7.96366714 7.76328248 4.85083365]
 [3.88361003 2.07274777 5.71397838]
 [1.65805202 6.4453212  1.98773397]]

Second 3x3 block:
[[7.76328248 4.85083365 3.12561818]
 [2.07274777 5.71397838 3.64526341]
 [6.4453212  1.98773397 4.47581694]]


#### 69. How to get the n largest values of an array (★★★)

In [74]:
import numpy as np
my_list = [10, 5, 8, 20, 1, 6]
n_largest = sorted(my_list, reverse=True)[:1]
print(n_largest)

[20]


#### 70. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [76]:
Z=np.array([2,3,4])
method_1=np.power(Z,3)
print("method 1 : ",method_1)
method_2= Z**3
print("method 2 : ",method_2)
method_3=[x**3 for x in Z]
print("method 3 : " ,method_3)

method 1 :  [ 8 27 64]
method 2 :  [ 8 27 64]
method 3 :  [8, 27, 64]


#### 71. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [77]:
matrix = np.array([[1, 1, 1],[2, 2, 2],[3, 3, 4],[4, 4, 4],[5, 5, 6],[6, 6, 6],[7, 7, 8],[8, 8, 8],[9, 9, 9],[10, 10, 10]])

unequal_rows = matrix[~np.all(matrix == matrix[0], axis=1)]

print(unequal_rows)

[[ 2  2  2]
 [ 3  3  4]
 [ 4  4  4]
 [ 5  5  6]
 [ 6  6  6]
 [ 7  7  8]
 [ 8  8  8]
 [ 9  9  9]
 [10 10 10]]


#### 72. Given a two dimensional array, how to extract unique rows? (★★★)

In [78]:
arr=np.array([[1,2,4],[22,5,3],[1,2,4],[1,8,7]])
unique_row=np.unique(arr,axis=0)
print(arr)
print(unique_row)

[[ 1  2  4]
 [22  5  3]
 [ 1  2  4]
 [ 1  8  7]]
[[ 1  2  4]
 [ 1  8  7]
 [22  5  3]]


#### 73. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [79]:
A=np.array([2,4,6,8])
B=np.array([1,3,5,7])

inner=np.einsum('i,i->', A, B)
print("inner : ",inner)
print()
outer=np.einsum('i,j->ij', A, B)
print("outer : \n",outer)
print()
sum=np.einsum('i->i', A + B)
print("sum : ",sum)
print()
mul=np.einsum('i->i', A * B)
print("multiplication : ",mul)

inner :  100

outer : 
 [[ 2  6 10 14]
 [ 4 12 20 28]
 [ 6 18 30 42]
 [ 8 24 40 56]]

sum :  [ 3  7 11 15]

multiplication :  [ 2 12 30 56]
